cd bin
wget https://pasgal-bs.cs.ucr.edu/bin/DBLP_sym.bin
wget https://pasgal-bs.cs.ucr.edu/bin/Epinions1_sym.bin
wget https://pasgal-bs.cs.ucr.edu/bin/Germany_sym.bin
wget https://pasgal-bs.cs.ucr.edu/bin/HepPh_sym.bin
wget https://pasgal-bs.cs.ucr.edu/bin/NotreDame_sym.bin
wget https://pasgal-bs.cs.ucr.edu/bin/RoadUSA_sym.bin
wget https://pasgal-bs.cs.ucr.edu/bin/Slashdot_sym.bin
wget https://pasgal-bs.cs.ucr.edu/bin/WikiTalk_sym.bin
wget https://pasgal-bs.cs.ucr.edu/bin/africa_sym.bin
wget https://pasgal-bs.cs.ucr.edu/bin/arabic_sym.bin
wget https://pasgal-bs.cs.ucr.edu/bin/asia_sym.bin
wget https://pasgal-bs.cs.ucr.edu/bin/com-orkut_sym.bin
wget https://pasgal-bs.cs.ucr.edu/bin/com-youtube_sym.bin
wget https://pasgal-bs.cs.ucr.edu/bin/enwiki-2023_sym.bin
wget https://pasgal-bs.cs.ucr.edu/bin/eu-2015-host_sym.bin
wget https://pasgal-bs.cs.ucr.edu/bin/europe_sym.bin
wget https://pasgal-bs.cs.ucr.edu/bin/flickr_sym.bin
wget https://pasgal-bs.cs.ucr.edu/bin/friendster_sym.bin
wget https://pasgal-bs.cs.ucr.edu/bin/grid_1000_100000_sym.bin
wget https://pasgal-bs.cs.ucr.edu/bin/hollywood_2009_sym.bin
wget https://pasgal-bs.cs.ucr.edu/bin/hugebubbles-00020_sym.bin
wget https://pasgal-bs.cs.ucr.edu/bin/hugetrace-00020_sym.bin
wget https://pasgal-bs.cs.ucr.edu/bin/in_2004_sym.bin
wget https://pasgal-bs.cs.ucr.edu/bin/indochina_sym.bin
wget https://pasgal-bs.cs.ucr.edu/bin/north-america_sym.bin
wget https://pasgal-bs.cs.ucr.edu/bin/planet_sym.bin
wget https://pasgal-bs.cs.ucr.edu/bin/roadNet-CA_sym.bin
wget https://pasgal-bs.cs.ucr.edu/bin/sd_arc_sym.bin
wget https://pasgal-bs.cs.ucr.edu/bin/skitter_sym.bin
wget https://pasgal-bs.cs.ucr.edu/bin/soc-LiveJournal1_sym.bin
wget https://pasgal-bs.cs.ucr.edu/bin/socfb-konect_sym.bin
wget https://pasgal-bs.cs.ucr.edu/bin/socfb-uci-uni_sym.bin
wget https://pasgal-bs.cs.ucr.edu/bin/twitter_sym.bin
wget https://pasgal-bs.cs.ucr.edu/bin/uk-2002_sym.bin
wget https://pasgal-bs.cs.ucr.edu/bin/us_sym.bin
wget https://pasgal-bs.cs.ucr.edu/bin/web-Google_sym.bin
